spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maple_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: maple
    password: maplepass
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /resources/**
    favicon:
      enabled: false
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    restart:
      enabled: true

mybatis:
  config: mybatis-config.xml
  type-aliases-package: com.nexon.maple.model
  mapper-locations: classpath:mybatis/**/*.xml

jwt:
  grade: grade
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  type: bearer
  header: Authorization

